<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>DBDocs</title>

<link type="text/css" rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css" />
<link type="text/css" rel="stylesheet" href="assets/chosen/chosen/chosen.css" />

<style type="text/css">
	body {
		padding-top: 60px;
		padding-bottom: 40px;
	}
	.hashlink {
		background: #ffffbb !important;
	}
</style>

<link type="text/css" rel="stylesheet" href="assets/bootstrap/css/bootstrap-responsive.min.css" />

<?php if (($webfont = Config::get('dbdocs.webfont', false)) !== false): ?>

<link href="http://fonts.googleapis.com/css?family=<?php echo urlencode($webfont); ?>" rel="stylesheet" type="text/css">
<style>
body { font-family: "<?php echo $webfont; ?>", sans-serif; }
</style>

<?php endif; ?>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/chosen/chosen/chosen.jquery.min.js"></script>
<script src="assets/quicksearch/jquery.quicksearch.js"></script>
<script type="text/javascript">
$(document).ready(function () {
	$("._extra").tooltip({
		"html" : true,
		"title" : "PK : Primary key<br />UI : Unique<br />I : Index<br />AI : Auto increment<br />FK : Foreign key<br />UN : Unsigned",
		"placement" : "right"
	});
	$("._foreign_key").tooltip({
		"placement" : "right"
	});

	var chosen_json = <?php echo $chosen_json; ?>;

	$.each(chosen_json.tables, function(index, array) {
		$("#_global_search_tables").append(new Option(array["text"], array["href"]));
	});
	$.each(chosen_json.columns, function(index, array) {
		$("#_global_search_columns").append(new Option(array["text"], array["href"]));
	});
	$.each(chosen_json.indexes, function(index, array) {
		$("#_global_search_indexes").append(new Option(array["text"], array["href"]));
	});
	$.each(chosen_json.views, function(index, array) {
		$("#_global_search_views").append(new Option(array["text"], array["href"]));
	});
	$("#_global_search").chosen().change(function(e) {
		window.location = $(this).val();
	});
});
</script>

</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container-fluid">

<a class="brand" href="index.html">DBDocs <?php echo e(Dbdocs::VERSION); ?></a>
<ul class="nav">
<li<?php $active === 'tables' and print(' class="active"'); ?>><a href="tables.html">Tables</a></li>
<li<?php $active === 'indexes' and print(' class="active"'); ?>><a href="indexes.html">Indexes</a></li>
<li<?php $active === 'views' and print(' class="active"'); ?>><a href="views.html">Views</a></li>
</ul>
<form class="navbar-form pull-left" style="margin-top:8px;">
<select id="_global_search" data-placeholder="Search" style="width:500px;" />
<option value=""></option>
<optgroup id="_global_search_tables" label="Tables"></optgroup>
<optgroup id="_global_search_columns" label="Columns"></optgroup>
<optgroup id="_global_search_indexes" label="Indexes"></optgroup>
<optgroup id="_global_search_views" label="Views"></optgroup>
</select>
</form>

<ul class="nav pull-right">
<li><a href="https://github.com/mp-php/fuel-dbdocs/issues" target="_blank">Issues</a></li>
</ul>

</div><!--/container-fluid-->
</div><!--/navbar-inner-->
</div><!--/navbar-->

<div class="container">

<?php echo $content; ?>

<hr />

<footer>
<p class="pull-left">
<?php echo Html::anchor('https://github.com/mp-php/fuel-dbdocs', 'DBDocs', array('target' => '_blank')); ?>
 developed by <?php echo Html::anchor('http://madroom-project.blogspot.jp/', 'madroom project', array('target' => '_blank')); ?>
</p>

<p class="pull-right">
Generated by <?php echo Html::anchor('http://fuelphp.com/', 'FuelPHP', array('target' => '_blank')); ?> <?php echo e(Fuel::VERSION); ?>
 and using <?php echo Html::anchor('http://twitter.github.com/bootstrap/', 'Twitter Bootstrap', array('target' => '_blank')); ?>
</p>
</footer>

</div><!--/.container-->

</body>
</html>
