<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>DBDocs</title>

<?php echo Asset::css('bootstrap.min.css'); ?>

<style type="text/css">
	body {
		padding-top: 60px;
		padding-bottom: 40px;
	}
	.sidebar-nav {
		padding: 9px 0;
	}
</style>

<?php echo Asset::css('bootstrap-responsive.min.css'); ?>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<?php echo Asset::js('bootstrap.min.js'); ?>

</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container-fluid">

<a class="brand" href="<?php echo Uri::base(); ?>">DBDocs</a>
<ul class="nav">
	<li<?php $active === 'generate' and print(' class="active"'); ?>><?php echo Html::anchor('index/generate', 'Generate'); ?></li>
</ul>

<ul class="nav pull-right">
<li><a href="https://github.com/mp-php/fuel-dbdocs/issues" target="_blank">Issues</a></li>
</ul>

</div><!--/container-fluid-->
</div><!--/navbar-inner-->
</div><!--/navbar-->

<div class="container">

<?php if (Session::get_flash('success')): ?>
<div class="alert alert-success">
<button class="close" data-dismiss="alert">×</button>
<p><?php echo implode('</p><p>', e((array) Session::get_flash('success'))); ?></p>
</div>
<?php endif; ?>
<?php if (Session::get_flash('error')): ?>
<div class="alert alert-error">
<button class="close" data-dismiss="alert">×</button>
<p><?php echo implode('</p><p>', e((array) Session::get_flash('error'))); ?></p>
</div>
<?php endif; ?>

<?php echo $content; ?>

<hr/>

<footer>
<p class="pull-left">
<?php echo Html::anchor('https://github.com/mp-php/fuel-dbdocs', 'DBDocs', array('target' => '_blank')); ?>
 developed by <?php echo Html::anchor('http://madroom-project.blogspot.jp/', 'madroom project', array('target' => '_blank')); ?>
</p>

<p class="pull-right">
Generated by <?php echo Html::anchor('http://fuelphp.com/', 'FuelPHP', array('target' => '_blank')); ?> <?php echo e(Fuel::VERSION); ?>
 and using <?php echo Html::anchor('http://twitter.github.com/bootstrap/', 'Twitter Bootstrap', array('target' => '_blank')); ?>
</p>
</footer>

</div><!--/.container-->

</html>
